version: '3.4'

services:
  # Catalog Application
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  # Catalog Database
  catalogdb:
    image: postgres

  # Basket Application
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  # Basket Database
  basketdb:
    image: postgres

  # Discount gRPC
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  # RedisDB
  distributedcache:
    image: redis

  # Ordering Application
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  # Order Database
  orderdb:
    image: mcr.microsoft.com/mssql/server

  # RabbitMQ
  messagebroker:
    image: rabbitmq:management

  # YARP API Gateway
  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog:    
  postgres_basket: